name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 1. Action runs every time you push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      
      # Setup Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 

      # Install dependencies (looks at package.json)
      - name: Install dependencies
        run: npm install

      # Build the Vue project (runs 'npm run build' and creates the 'dist' folder)
      - name: Build project
        run: npm run build
      
      # Deploy the contents of the dist folder to GitHub Pages
      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 2. Tells GitHub to publish the final built code
          publish_branch: gh-pages # 3. The branch GitHub Pages watches